### ISSUE TITLE
Multiple species groups

### ISSUE THREAD

**Issue by stianlik** [cdproject8/Artsdatabanken#47]
At the moment our app only supports birds (I think?), all the category-buttons go to the same page. We need to make the system more general, most of the code can be used in the same manner for all categories. Talk to Andreas about the state of the user interface.

**Comment by skotsjedal** [comment]
based on an argument passed to the constructor for the observation (that's already there but not being used atm) and loading the correct autocomplete, and possibly different fields ?

**Comment by skotsjedal** [comment]
Partially implemented it now, it's saved and all, it remains for you to implement the autocomplete together with this

**Comment by skotsjedal** [comment]
Implemented
