### ISSUE TITLE
Camera [F5]

### ISSUE THREAD

**Issue by skotsjedal** [cdproject8/Artsdatabanken#51]
Implement the camera into the final solution

code is partially already there, ask Anders

**Comment by andersrye** [comment]
on it.

**Comment by skotsjedal** [comment]
cool story bro

**Comment by skotsjedal** [comment]
According to Anders the application camera code is functional, however the plugin code for exporting the images makes the email application force close so something is wrong. Maybe the email app doesn't have access to local files ? Or just a bug.

Normal export should still work but I've not tested it

the image-attachment code is based on result 1 of http://stackoverflow.com/questions/2264622/android-multiple-email-attachments-using-intent

An extention of the original WebIntent plugin i found

**Comment by skotsjedal** [comment]
works with one image (current functionality consists of sending the last found image only)
For those who managed to implement this with several images found that many (if not most) applications don't support getting several images anyway

look into creating a zipfile

EDIT: ok so now I actually got it working in the end after some "help from my friends"

But!
if you do not have the gmail app (or possibly some other that supports Intent.type 'application/octet-stream' )
You will not be able to export an observation with images
